version: '3.9'

services:

  app:
    image: johannag01/tapup:1.0.0
    container_name: tapup-app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "8080:8080"